"use client";

import { useEffect, useMemo, useState } from "react";
import type { Route, RouteStop, Stop, Vehicle } from "@/types";

type Tab = "overview" | "vehicles" | "routes" | "stops";
type Notice = { kind: "success" | "error"; message: string } | null;

async function api<T>(url: string, options?: RequestInit): Promise<T> {
  const response = await fetch(url, { headers: { "Content-Type": "application/json" }, ...options });
  if (!response.ok) {
    const body = await response.json().catch(() => null);
    throw new Error(body?.error?.message || "เกิดข้อผิดพลาดจาก Backend");
  }
  return response.status === 204 ? (undefined as T) : response.json();
}

const blankVehicle = { name: "", type: "", routeId: "", latitude: "", longitude: "", isActive: true };
const blankRoute = { name: "", color: "#165DFF", isActive: true };
const blankStop = { nameTh: "", nameEn: "", latitude: "", longitude: "", imageUrl: "", isActive: true };

export default function AdminDashboard() {
  const [tab, setTab] = useState<Tab>("overview");
  const [routes, setRoutes] = useState<Route[]>([]);
  const [vehicles, setVehicles] = useState<Vehicle[]>([]);
  const [stops, setStops] = useState<Stop[]>([]);
  const [selectedRouteId, setSelectedRouteId] = useState<number | null>(null);
  const [routeStops, setRouteStops] = useState<RouteStop[]>([]);
  const [notice, setNotice] = useState<Notice>(null);
  const [editingId, setEditingId] = useState<number | null>(null);
  const [vehicleForm, setVehicleForm] = useState(blankVehicle);
  const [routeForm, setRouteForm] = useState(blankRoute);
  const [stopForm, setStopForm] = useState(blankStop);
  const [newRouteStopId, setNewRouteStopId] = useState("");

  const selectedRoute = routes.find((route) => route.id === selectedRouteId) || null;
  const unassignedStops = useMemo(() => stops.filter((stop) => !routeStops.some((item) => item.stopId === stop.id)), [stops, routeStops]);

  const refresh = async () => {
    const [nextRoutes, nextVehicles, nextStops] = await Promise.all([api<Route[]>("/api/routes"), api<Vehicle[]>("/api/vehicles"), api<Stop[]>("/api/stops")]);
    setRoutes(nextRoutes); setVehicles(nextVehicles); setStops(nextStops);
    if (selectedRouteId && nextRoutes.some((route) => route.id === selectedRouteId)) setRouteStops(await api<RouteStop[]>(`/api/routes/${selectedRouteId}/stops`));
    else if (selectedRouteId) { setSelectedRouteId(null); setRouteStops([]); }
  };

  useEffect(() => { refresh().catch((error) => setNotice({ kind: "error", message: error.message })); }, []);

  const run = async (action: () => Promise<void>, success = "บันทึกข้อมูลเรียบร้อย") => {
    try { await action(); await refresh(); setNotice({ kind: "success", message: success }); } catch (error) { setNotice({ kind: "error", message: error instanceof Error ? error.message : "เกิดข้อผิดพลาด" }); }
  };

  const selectRoute = async (route: Route) => {
    setSelectedRouteId(route.id); setEditingId(route.id); setRouteForm({ name: route.name, color: route.color || "#165DFF", isActive: route.isActive });
    try { setRouteStops(await api<RouteStop[]>(`/api/routes/${route.id}/stops`)); } catch (error) { setNotice({ kind: "error", message: error instanceof Error ? error.message : "โหลด RouteStop ไม่สำเร็จ" }); }
  };

  const resetForm = () => { setEditingId(null); setVehicleForm(blankVehicle); setRouteForm(blankRoute); setStopForm(blankStop); };
  const tabLabel: Record<Tab, string> = { overview: "Overview", vehicles: "Vehicles", routes: "Routes", stops: "Stops" };

  return <div className="admin-layout"><aside className="admin-sidebar"><h1>Operations</h1><p>Campus transport control room</p><nav className="side-nav">{(Object.keys(tabLabel) as Tab[]).map((item) => <button type="button" key={item} className={tab === item ? "active" : ""} aria-current={tab === item ? "page" : undefined} onClick={() => { setTab(item); resetForm(); }}><NavIcon name={item} />{tabLabel[item]}</button>)}</nav></aside><main className="admin-main"><div className="admin-heading"><div><div className="eyebrow">Sprint 01 / data foundation</div><h1>{tab === "overview" ? "Network overview" : `${tabLabel[tab]} management`}</h1><p>จัดการข้อมูลที่เชื่อมต่อกับ Backend API และฐานข้อมูลกลาง</p></div><a className="button button-secondary" href="/api/health" target="_blank" rel="noreferrer">API health</a></div>{notice && <div className={`alert ${notice.kind === "error" ? "alert-error" : "alert-success"}`} style={{ marginBottom: 18 }} role="status">{notice.message}</div>}

{tab === "overview" && <Overview routes={routes} vehicles={vehicles} stops={stops} onRoutes={() => setTab("routes")} />}
{tab === "vehicles" && <div className="admin-columns"><EntityPanel title="Vehicles" subtitle="ยานพาหนะทั้งหมดในระบบ" count={vehicles.length}><VehicleTable vehicles={vehicles} onEdit={(vehicle) => { setEditingId(vehicle.id); setVehicleForm({ name: vehicle.name, type: vehicle.type || "", routeId: vehicle.routeId?.toString() || "", latitude: vehicle.latitude == null ? "" : String(vehicle.latitude), longitude: vehicle.longitude == null ? "" : String(vehicle.longitude), isActive: vehicle.isActive }); }} onDelete={(id) => run(() => api(`/api/vehicles/${id}`, { method: "DELETE" }).then(() => undefined), "ลบ Vehicle แล้ว")} /></EntityPanel><PanelForm title={editingId ? "แก้ไข Vehicle" : "เพิ่ม Vehicle"} onCancel={resetForm} onSubmit={() => run(() => api(`/api/vehicles${editingId ? `/${editingId}` : ""}`, { method: editingId ? "PATCH" : "POST", body: JSON.stringify({ name: vehicleForm.name, type: vehicleForm.type || null, routeId: vehicleForm.routeId ? Number(vehicleForm.routeId) : null, latitude: vehicleForm.latitude === "" ? null : Number(vehicleForm.latitude), longitude: vehicleForm.longitude === "" ? null : Number(vehicleForm.longitude), isActive: vehicleForm.isActive }) }).then(() => { resetForm(); }), editingId ? "แก้ไข Vehicle แล้ว" : "เพิ่ม Vehicle แล้ว")}><div className="field"><label>ชื่อ Vehicle *</label><input value={vehicleForm.name} onChange={(e) => setVehicleForm({ ...vehicleForm, name: e.target.value })} placeholder="เช่น RSU Shuttle 04" /></div><div className="field"><label>ประเภท</label><input value={vehicleForm.type} onChange={(e) => setVehicleForm({ ...vehicleForm, type: e.target.value })} placeholder="Electric Van" /></div><div className="field"><label>Route ที่ผูก</label><select value={vehicleForm.routeId} onChange={(e) => setVehicleForm({ ...vehicleForm, routeId: e.target.value })}><option value="">ยังไม่กำหนด</option>{routes.map((route) => <option value={route.id} key={route.id}>{route.name}</option>)}</select></div><div className="form-grid"><div className="field"><label>Latitude รถ</label><input type="number" step="any" value={vehicleForm.latitude} onChange={(e) => setVehicleForm({ ...vehicleForm, latitude: e.target.value })} placeholder="13.9552" /></div><div className="field"><label>Longitude รถ</label><input type="number" step="any" value={vehicleForm.longitude} onChange={(e) => setVehicleForm({ ...vehicleForm, longitude: e.target.value })} placeholder="100.5851" /></div></div><p className="form-hint">กรอกพิกัดทั้งสองช่องเพื่อให้รถแสดงบน Public Web</p><label className="checkbox"><input type="checkbox" checked={vehicleForm.isActive} onChange={(e) => setVehicleForm({ ...vehicleForm, isActive: e.target.checked })} /> เปิดใช้งาน</label></PanelForm></div>}

{tab === "routes" && <div className="admin-columns"><EntityPanel title="Routes" subtitle="เส้นทางและการเรียงลำดับจุดจอด" count={routes.length}><RouteTable routes={routes} selectedId={selectedRouteId} onSelect={selectRoute} onDelete={(id) => run(() => api(`/api/routes/${id}`, { method: "DELETE" }).then(() => undefined), "ลบ Route แล้ว")} /></EntityPanel><div><PanelForm title={editingId ? "แก้ไข Route" : "เพิ่ม Route"} onCancel={resetForm} onSubmit={() => run(() => api(`/api/routes${editingId ? `/${editingId}` : ""}`, { method: editingId ? "PATCH" : "POST", body: JSON.stringify(routeForm) }).then(() => { resetForm(); }), editingId ? "แก้ไข Route แล้ว" : "เพิ่ม Route แล้ว")}><div className="field"><label>ชื่อ Route *</label><input value={routeForm.name} onChange={(e) => setRouteForm({ ...routeForm, name: e.target.value })} placeholder="เช่น North Campus" /></div><div className="field"><label>สี Route</label><input type="color" value={routeForm.color} onChange={(e) => setRouteForm({ ...routeForm, color: e.target.value })} style={{ height: 40, padding: 4 }} /></div><label className="checkbox"><input type="checkbox" checked={routeForm.isActive} onChange={(e) => setRouteForm({ ...routeForm, isActive: e.target.checked })} /> เปิดให้ผู้โดยสารเห็น</label></PanelForm>{selectedRoute && <RouteStopEditor route={selectedRoute} routeStops={routeStops} availableStops={unassignedStops} newStopId={newRouteStopId} setNewStopId={setNewRouteStopId} onAdd={() => run(() => api(`/api/routes/${selectedRoute.id}/stops`, { method: "POST", body: JSON.stringify({ stopId: Number(newRouteStopId) }) }).then(() => undefined), "เพิ่ม Stop เข้า Route แล้ว")} onRemove={(stopId) => run(() => api(`/api/routes/${selectedRoute.id}/stops/${stopId}`, { method: "DELETE" }).then(() => undefined), "นำ Stop ออกจาก Route แล้ว")} onReorder={(next) => run(() => api(`/api/routes/${selectedRoute.id}/stops/reorder`, { method: "PATCH", body: JSON.stringify({ stopIds: next.map((item) => item.stopId) }) }).then(() => undefined), "บันทึกลำดับ Stop แล้ว")} />}</div></div>}

{tab === "stops" && <div className="admin-columns"><EntityPanel title="Stops" subtitle="จุดจอดพร้อมพิกัดสำหรับแผนที่" count={stops.length}><StopTable stops={stops} onEdit={(stop) => { setEditingId(stop.id); setStopForm({ nameTh: stop.nameTh, nameEn: stop.nameEn || "", latitude: String(stop.latitude), longitude: String(stop.longitude), imageUrl: stop.imageUrl || "", isActive: stop.isActive }); }} onDelete={(id) => run(() => api(`/api/stops/${id}`, { method: "DELETE" }).then(() => undefined), "ลบ Stop แล้ว")} /></EntityPanel><PanelForm title={editingId ? "แก้ไข Stop" : "เพิ่ม Stop"} onCancel={resetForm} onSubmit={() => run(() => api(`/api/stops${editingId ? `/${editingId}` : ""}`, { method: editingId ? "PATCH" : "POST", body: JSON.stringify({ nameTh: stopForm.nameTh, nameEn: stopForm.nameEn || null, latitude: Number(stopForm.latitude), longitude: Number(stopForm.longitude), imageUrl: stopForm.imageUrl || null, isActive: stopForm.isActive }) }).then(() => { resetForm(); }), editingId ? "แก้ไข Stop แล้ว" : "เพิ่ม Stop แล้ว")}><div className="field"><label>ชื่อไทย *</label><input value={stopForm.nameTh} onChange={(e) => setStopForm({ ...stopForm, nameTh: e.target.value })} placeholder="เช่น อาคารหอพัก" /></div><div className="field"><label>ชื่ออังกฤษ</label><input value={stopForm.nameEn} onChange={(e) => setStopForm({ ...stopForm, nameEn: e.target.value })} placeholder="Residence Hall" /></div><div className="form-grid"><div className="field"><label>Latitude *</label><input type="number" step="any" value={stopForm.latitude} onChange={(e) => setStopForm({ ...stopForm, latitude: e.target.value })} placeholder="13.9552" /></div><div className="field"><label>Longitude *</label><input type="number" step="any" value={stopForm.longitude} onChange={(e) => setStopForm({ ...stopForm, longitude: e.target.value })} placeholder="100.5851" /></div></div><div className="field"><label>Image URL</label><input value={stopForm.imageUrl} onChange={(e) => setStopForm({ ...stopForm, imageUrl: e.target.value })} /></div><label className="checkbox"><input type="checkbox" checked={stopForm.isActive} onChange={(e) => setStopForm({ ...stopForm, isActive: e.target.checked })} /> เปิดใช้งาน</label></PanelForm></div>}
</main></div>;
}

function NavIcon({ name }: { name: Tab }) {
  if (name === "overview") return <svg aria-hidden="true" viewBox="0 0 24 24" fill="none"><rect x="4" y="4" width="6" height="6" rx="1" stroke="currentColor" strokeWidth="1.8" /><rect x="14" y="4" width="6" height="6" rx="1" stroke="currentColor" strokeWidth="1.8" /><rect x="4" y="14" width="6" height="6" rx="1" stroke="currentColor" strokeWidth="1.8" /><rect x="14" y="14" width="6" height="6" rx="1" stroke="currentColor" strokeWidth="1.8" /></svg>;
  if (name === "vehicles") return <svg aria-hidden="true" viewBox="0 0 24 24" fill="none"><path d="M5 16.5V9.8a2 2 0 0 1 1.6-2l1.2-.25.8-2.05A2 2 0 0 1 10.47 4h3.06a2 2 0 0 1 1.87 1.5l.8 2.05 1.2.25a2 2 0 0 1 1.6 2v6.7" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" /><path d="M4 16.5h16M7.5 19.5h.01M16.5 19.5h.01M7 11h10" stroke="currentColor" strokeWidth="2" strokeLinecap="round" /></svg>;
  if (name === "routes") return <svg aria-hidden="true" viewBox="0 0 24 24" fill="none"><circle cx="6" cy="18" r="2.5" stroke="currentColor" strokeWidth="1.8" /><circle cx="18" cy="6" r="2.5" stroke="currentColor" strokeWidth="1.8" /><path d="M8.5 18h2a5 5 0 0 0 5-5V8.5" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" /></svg>;
  return <svg aria-hidden="true" viewBox="0 0 24 24" fill="none"><path d="M18 10c0 4.5-6 10-6 10S6 14.5 6 10a6 6 0 1 1 12 0Z" stroke="currentColor" strokeWidth="1.8" /><circle cx="12" cy="10" r="2" stroke="currentColor" strokeWidth="1.8" /></svg>;
}

function Overview({ routes, vehicles, stops, onRoutes }: { routes: Route[]; vehicles: Vehicle[]; stops: Stop[]; onRoutes: () => void }) { return <><div className="metrics"><div className="metric"><div className="metric-label">Active routes</div><div className="metric-value">{routes.filter((item) => item.isActive).length}</div></div><div className="metric"><div className="metric-label">Active vehicles</div><div className="metric-value">{vehicles.filter((item) => item.isActive).length}</div></div><div className="metric"><div className="metric-label">Mapped stops</div><div className="metric-value">{stops.length}</div></div></div><div className="panel"><div className="section-heading" style={{ marginTop: 0 }}><div><h2>Route coverage</h2><p>เส้นทางที่ Backend พร้อมให้ Public Web ใช้งาน</p></div><button type="button" className="button button-secondary" onClick={onRoutes}>Manage routes →</button></div><div className="stop-list">{routes.map((route) => <div className="stop-item" key={route.id}><i className="route-swatch" style={{ background: route.color || "var(--blue)" }} /><div><div className="stop-name">{route.name}</div><div className="stop-en">{route._count?.routeStops || 0} stops · {route._count?.vehicles || 0} vehicles</div></div><span className={`status ${route.isActive ? "active" : "inactive"}`}>{route.isActive ? "Active" : "Draft"}</span></div>)}</div></div></>; }
function EntityPanel({ title, subtitle, count, children }: { title: string; subtitle: string; count: number; children: React.ReactNode }) { return <div className="panel"><div className="panel-title"><div><h2 style={{ margin: 0, fontSize: 20 }}>{title}</h2><p style={{ color: "var(--muted)", fontSize: 13, margin: "3px 0 0" }}>{subtitle}</p></div><span className="status active">{count}</span></div><div className="table-wrap">{children}</div></div>; }
function PanelForm({ title, children, onSubmit, onCancel }: { title: string; children: React.ReactNode; onSubmit: () => void; onCancel: () => void }) { return <div className="panel form"><h3>{title}</h3>{children}<div className="form-actions"><button className="button button-ghost" onClick={onCancel}>ล้าง</button><button className="button button-primary" onClick={onSubmit}>บันทึก</button></div></div>; }
function VehicleTable({ vehicles, onEdit, onDelete }: { vehicles: Vehicle[]; onEdit: (v: Vehicle) => void; onDelete: (id: number) => void }) { return <table><thead><tr><th>Vehicle</th><th>Route</th><th>Location</th><th>Status</th><th /></tr></thead><tbody>{vehicles.map((v) => <tr key={v.id}><td><strong>{v.name}</strong><br /><small style={{ color: "var(--muted)" }}>{v.type || "—"}</small></td><td>{v.route?.name || "Unassigned"}</td><td className="coords">{v.latitude != null && v.longitude != null ? `${Number(v.latitude).toFixed(4)}, ${Number(v.longitude).toFixed(4)}` : "No GPS"}</td><td><span className={`status ${v.isActive ? "active" : "inactive"}`}>{v.isActive ? "Active" : "Offline"}</span></td><td><div className="row-actions"><button className="icon-button" onClick={() => onEdit(v)}>Edit</button><button className="icon-button" onClick={() => onDelete(v.id)}>Delete</button></div></td></tr>)}</tbody></table>; }
function RouteTable({ routes, selectedId, onSelect, onDelete }: { routes: Route[]; selectedId: number | null; onSelect: (r: Route) => void; onDelete: (id: number) => void }) { return <table><thead><tr><th>Route</th><th>Stops</th><th>Status</th><th /></tr></thead><tbody>{routes.map((r) => <tr key={r.id} style={{ background: selectedId === r.id ? "var(--mint)" : undefined }}><td><strong><i className="route-swatch" style={{ background: r.color || "var(--blue)", marginRight: 7 }} />{r.name}</strong></td><td>{r._count?.routeStops || 0}</td><td><span className={`status ${r.isActive ? "active" : "inactive"}`}>{r.isActive ? "Public" : "Draft"}</span></td><td><div className="row-actions"><button type="button" className="icon-button" onClick={() => onSelect(r)}>Edit</button><button type="button" className="icon-button" onClick={() => onDelete(r.id)}>Delete</button></div></td></tr>)}</tbody></table>; }
function StopTable({ stops, onEdit, onDelete }: { stops: Stop[]; onEdit: (s: Stop) => void; onDelete: (id: number) => void }) { return <table><thead><tr><th>Stop</th><th>Coordinates</th><th>Status</th><th /></tr></thead><tbody>{stops.map((s) => <tr key={s.id}><td><strong>{s.nameTh}</strong><br /><small style={{ color: "var(--muted)" }}>{s.nameEn || "—"}</small></td><td className="coords">{Number(s.latitude).toFixed(5)},<br />{Number(s.longitude).toFixed(5)}</td><td><span className={`status ${s.isActive ? "active" : "inactive"}`}>{s.isActive ? "Active" : "Hidden"}</span></td><td><div className="row-actions"><button className="icon-button" onClick={() => onEdit(s)}>Edit</button><button className="icon-button" onClick={() => onDelete(s.id)}>Delete</button></div></td></tr>)}</tbody></table>; }
function RouteStopEditor({ route, routeStops, availableStops, newStopId, setNewStopId, onAdd, onRemove, onReorder }: { route: Route; routeStops: RouteStop[]; availableStops: Stop[]; newStopId: string; setNewStopId: (value: string) => void; onAdd: () => void; onRemove: (stopId: number) => void; onReorder: (items: RouteStop[]) => void }) { const move = (index: number, direction: -1 | 1) => { const next = [...routeStops]; [next[index], next[index + direction]] = [next[index + direction], next[index]]; onReorder(next); }; return <div className="panel route-editor"><div className="panel-title"><span>Stops in {route.name}</span><span className="status active">{routeStops.length}</span></div><div className="form-grid" style={{ marginBottom: 13 }}><select value={newStopId} onChange={(e) => setNewStopId(e.target.value)}><option value="">เลือก Stop เพื่อเพิ่ม…</option>{availableStops.map((stop) => <option key={stop.id} value={stop.id}>{stop.nameTh} · {stop.nameEn || ""}</option>)}</select><button className="button button-secondary" disabled={!newStopId} onClick={onAdd}>+ Add stop</button></div>{routeStops.length === 0 ? <div className="empty-state">ยังไม่มี Stop ใน Route นี้</div> : <div className="ordered-list">{routeStops.map((item, index) => <div className="ordered-row" key={item.id}><span className="stop-number">{index + 1}</span><div><strong>{item.stop.nameTh}</strong><div className="stop-en">{item.stop.nameEn || "English name unavailable"}</div></div><div className="order-actions"><button disabled={index === 0} onClick={() => move(index, -1)} title="เลื่อนขึ้น">↑</button><button disabled={index === routeStops.length - 1} onClick={() => move(index, 1)} title="เลื่อนลง">↓</button><button onClick={() => onRemove(item.stopId)} title="นำออก">×</button></div></div>)}</div>}</div>; }
